name: JSON Converter

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0点自动运行

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      SOURCE_URL: 'https://www.ikunzy.com/'  # 你的接口地址

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run conversion
      run: python convert.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: false
